repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-json
    -   id: debug-statements
    -   id: fix-encoding-pragma
    -   id: file-contents-sorter
        files: ^(requirements.txt|\.gitignore|\.dockerignore)$
    -   id: requirements-txt-fixer
    -   id: pretty-format-json
        args: [--autofix]
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: 'v0.790'
#     hooks:
#     -   id: mypy
#         args: [--ignore-missing-imports]
-   repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3.8
- repo: https://github.com/humitos/mirrors-autoflake.git
  rev: v1.3
  hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
    -   id: flake8
        args:
            - --max-line-length=88
            - --ignore=E402,W503
